sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - env: BUILD=DEBUG
      compiler: gcc

    - env: BUILD=RELEASE
      compiler: gcc

    - env: BUILD=DEBUG
      compiler: clang

    - env: BUILD=RELEASE
      compiler: clang

addons:
  apt:
    packages:
      - cmake
      - g++

# before_install:
#   - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang libc++-dev libc++abi-dev; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++"; fi
  - BOOST_V=1.62.0
  -  # Get and install Boost
  - PROJECT_DIR=`pwd`
  - BOOST=$HOME/boost
  - git clone --depth 1 -b boost-$BOOST_V https://github.com/boostorg/boost.git $BOOST
  - cd $BOOST
  - git submodule update --init --merge
  - ./bootstrap.sh
  - ./b2 headers
  - cd $PROJECT_DIR
  - export BOOST_ROOT=$BOOST

script:
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD} -DBOOST_ROOT="$BOOST"
  - make
  - ./test/test_tangle
