sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - env: BUILD=DEBUG
      compiler: gcc

    - env: BUILD=RELEASE
      compiler: gcc

    - env: BUILD=DEBUG
      compiler: clang

    - env: BUILD=RELEASE
      compiler: clang

addons:
  apt:
    packages:
      - cmake
      - g++

# before_install:
#   - sudo apt-get update -qq

install:
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang libc++-dev libc++abi-dev; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++"; fi

script:
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD}
  - make
  - ./test/test_tangle
